# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('length', models.IntegerField(default=0)),
                ('season', models.CharField(max_length=200)),
                ('activity_type', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(blank=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(default='null', max_length=200)),
                ('region', models.CharField(default='null', max_length=200)),
                ('country', models.CharField(default='null', max_length=200)),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Overview')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='overview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.User'),
        ),
    ]
