# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trip',
            new_name='Overview',
        ),
        migrations.RenameModel(
            old_name='Destination',
            new_name='Segments',
        ),
        migrations.RenameField(
            model_name='segments',
            old_name='trip',
            new_name='overview',
        ),
    ]
